# 1. Base Image
FROM python:3.10-slim

# 2. Set working directory
WORKDIR /app

# 3. Copy requirements first
COPY requirements.txt .

# 4. Install dependencies
# ADDED 'poppler-utils' for pdf2image to work
# KEPT 'libgomp1' for PaddleOCR
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt

# 5. Copy your code
COPY . .

# 6. Expose the port
EXPOSE 8000

# 7. Start the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]